name: playstation_ui
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  eva_icons_flutter: 2.0.1
  bottom_navy_bar: ^5.6.0
  flutter_swiper : ^1.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: BROADW
      fonts:
        - asset: assets/fonts/BROADW.TTF

  assets:
    - assets/images/
